export enum ActivepiecesPropertyType {
  SHORT_TEXT = "ShortText",
  LONG_TEXT = "LongText",
  CHECKBOX = "Checkbox",
  MARKDOWN = "Markdown",
  DATE_TIME = "DateTime",
  NUMBER = "Number",
  STATIC_DROPDOWN = "StaticDropdown",
  STATIC_MULTISELECT_DROPDOWN = "StaticMultiSelectDropdown",
  JSON = "Json",
  DICTIONARY = "Dictionary",
  FILE = "File",
  ARRAY_STRINGS = "ArrayStrings",
  ARRAY_FIELDS = "ArrayFields",
  DROPDOWN = "Dropdown",
  MULTISELECT_DROPDOWN = "MultiSelectDropdown",
  DYNAMIC_PROPERTIES = "DynamicProperties",
  CUSTOM = "Custom",
}
